### ISSUE TITLE
Unable to migrate pre 1.0 index using securityadmin.sh

### ISSUE THREAD

**Issue by vnil1994** [opensearch-project/security#104]
Hi,

I am upgrading a pre 1.0 opendistro kubernetes installation and i am following the guide here: https://opendistro.github.io/for-elasticsearch-docs/docs/upgrade/1-0-0/

I have successfully backup the files in question using the securityadmin.sh. Then i updated the deployment files to use the latest opendistro image and redeployed. The elasticsearch node seems to be starting OK (I can see that the node has been initialized.).

However, when i try to run the "migrate" option using securityadmin i get the following error:

```
[root@test-es01-5f74654dd8-j9l7x tools]# ./securityadmin.sh -migrate /root/backup -nhnv -cacert /usr/share/elasticsearch/config/root-ca.pem -cert /usr/share/elasticsearch/config/admin.pem -key /usr/share/elasticsearch/config/admin-key.pem
Open Distro Security Admin v7
Will connect to localhost:9300 ... done
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{kWx9xHcBTXuQi_htDOtLYw}{localhost}{127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:386)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.execute(OpenDistroSecurityAdmin.java:519)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main(OpenDistroSecurityAdmin.java:152)
```

What is the issue here?

**Comment by vnil1994** [comment]
I was able to run the migration command and see this when i run the migration command:

```
[root@test-es01-79cdc894b6-km4xb tools]# ./securityadmin.sh -migrate /root/pre-1.0.0.0 -icl -nhnv -cacert /usr/share/elasticsearch/config/root-ca.pem -cert /usr/share/elasticsearch/config/admin.pem -key /usr/share/elasticsearch/config/admin-key.pem
Open Distro Security Admin v7
Will connect to localhost:9300 ... done
Connected as REDACTED
Elasticsearch Version: 7.1.1
Open Distro Security Version: 1.1.0.0
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: test-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
INFO: .opendistro_security index state is YELLOW, it seems you miss some replicas
ERR: Seems cluster is already migrated
```

However, the logs are spewing out this:
```

[2019-08-06T09:15:48,758][ERROR][c.a.o.s.a.BackendRegistry] [test-es01] Not yet initialized (you may need to run securityadmin)
[2019-08-06T09:15:49,673][ERROR][c.a.o.s.c.ConfigurationRepository] [test-es01] com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory@342ee4f6 listener errored: StaticResourceException[Cannot override static roles]
com.amazon.opendistroforelasticsearch.security.configuration.StaticResourceException: Cannot override static roles
	at com.amazon.opendistroforelasticsearch.security.securityconf.DynamicConfigFactory.onChange(DynamicConfigFactory.java:130) ~[opendistro_security-1.1.0.0.jar:1.1.0.0]
	at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.notifyAboutChanges(ConfigurationRepository.java:308) [opendistro_security-1.1.0.0.jar:1.1.0.0]
	at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.reloadConfiguration0(ConfigurationRepository.java:297) [opendistro_security-1.1.0.0.jar:1.1.0.0]
	at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository.reloadConfiguration(ConfigurationRepository.java:280) [opendistro_security-1.1.0.0.jar:1.1.0.0]
	at com.amazon.opendistroforelasticsearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:197) [opendistro_security-1.1.0.0.jar:1.1.0.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Output from the --diagnose command from securityadmin.sh:

```
[root@test-es01-79cdc894b6-km4xb tools]# ./securityadmin.sh --diagnose -icl -nhnv -cacert /usr/share/elasticsearch/config/root-ca.pem -cert /usr/share/elasticsearch/config/admin.pem -key /usr/share/elasticsearch/config/admin-key.pem
Open Distro Security Admin v7
Will connect to localhost:9300 ... done
Connected as REDACTED
Elasticsearch Version: 7.1.1
Open Distro Security Version: 1.1.0.0
Diagnostic trace written to: /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin_diag_trace_2019-Aug-06_09-21-09.txt
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: test-cluster
Clusterstate: YELLOW
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
INFO: .opendistro_security index state is YELLOW, it seems you miss some replicas
Populate config from /usr/share/elasticsearch/plugins/opendistro_security/tools
ERR: Seems ./config.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./config.yml (No such file or directory)
ERR: Seems ./roles.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./roles.yml (No such file or directory)
ERR: Seems ./roles_mapping.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./roles_mapping.yml (No such file or directory)
ERR: Seems ./internal_users.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./internal_users.yml (No such file or directory)
ERR: Seems ./action_groups.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./action_groups.yml (No such file or directory)
ERR: Seems ./tenants.yml is not in Open Distro Security 7 format: java.io.FileNotFoundException: ./tenants.yml (No such file or directory)
ERR: cannot upload configuration, see errors above
```

**Comment by vnil1994** [comment]
I dont know what happened but the changed password for the admin user did not work so i guess the migration didnt work but at least the stack is up and running and i can send data to Elasticsearch and view the logs with kibana.

However, if i switch tenant to the "admin_tenant" i get the following error:

`{"message":"mapping set to strict, dynamic introduction of [references] within [doc] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [references] within [doc] is not allowed","statusCode":400,"error":"Bad Request"}`

How can i fix this?

**Comment by pawelw1** [comment]
@vnil1994 Have you found a solution to your issue?

**Comment by cliu123** [comment]
ODFE has already been archived. Please upgrade to or create OpenSearch clusters.
