### ISSUE TITLE
Wildcard in dls query during role definitions throwing exceptions

### ISSUE THREAD

**Issue by agarwalgovind** [opensearch-project/security#1040]
Created a role which will search for a particular type of dashboards - 

es_user:
  cluster_permissions:
    - '\*'
  index_permissions:
    - index_patterns:
      - '.kibana\*'
      allowed_actions:
        - '\*'
      dls: "{\"regexp\": {\"dashboard.title\": {\"value\": \"Dash_Start_\*\", \"boost\": 1.0, \"rewrite\": \"constant_score\"}}}"
  tenant_permissions:
    - tenant_patterns:
      - '\*'
      allowed_actions:
      - "kibana_read_only"

Ran securityadmin.sh to load the role definition into ES.

But getting an exception during login -
[2021-02-18T13:26:53,228][WARN ][r.suppressed             ] [] path: /.kibana/_doc/config%3A7.10.0-SNAPSHOT, params: {index=.kibana, id=config:7.10.0-SNAPSHOT}
org.elasticsearch.transport.RemoteTransportException: [][127.0.0.1:9300][indices:data/read/get[s]]
Caused by: java.lang.UnsupportedOperationException: Query dashboard.title:/Dash_Start_*/ does not implement createWeight
	at org.apache.lucene.search.Query.createWeight(Query.java:66) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:726) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:63) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:231) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:726) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:113) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:726) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsFlsFilterLeafReader$DlsGetEvaluator.<init>(DlsFlsFilterLeafReader.java:232) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsFlsFilterLeafReader.<init>(DlsFlsFilterLeafReader.java:214) ~[?:?]
	at com.amazon.opendistroforelasticsearch.security.configuration.DlsFlsFilterLeafReader$DlsFlsSubReaderWrapper.wrap(DlsFlsFilterLeafReader.java:349) ~[?:?]
	at org.apache.lucene.index.FilterDirectoryReader$SubReaderWrapper.wrap(FilterDirectoryReader.java:62) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]

Tried with different type of queries like - "query_string", "match_phrase_prefix", "wildcard". Same exception is coming.

**Comment by chrousto** [comment]
Hello,
you need to escape string within the dls declaration : this'll work :

```yaml
test:
  reserved: false
  index_permissions:
    - index_patterns:
      - '*'
      allowed_actions:
        - '*'
      dls: "{\"regexp\": {\"dashboard.title\": {\"value\": \"Dash_Start_*\", \"boost\": 1.0, \"rewrite\": \"constant_score\"}}}"
```

**Comment by agarwalgovind** [comment]
Hi @chrousto ,
I tried your suggestion but getting the same error -
  log   [16:47:46.529] [error][data][elasticsearch] [unsupported_operation_exception]: Query dashboard.title:/Dash_AML_*/ does not implement createWeight
  log   [16:47:46.531] [error][http] { ResponseError: Query dashboard.title:/Dash_Start_*/ does not implement createWeight: unsupported_operation_exception


`test:
  cluster_permissions:
    - '*'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - '*'
      dls: "{\"regexp\": {\"dashboard.title\": {\"value\": \"Dash_Start_*\", \"boost\": 1.0, \"rewrite\": \"constant_score\"}}}"
  tenant_permissions:
    - tenant_patterns:
        - '*'
      allowed_actions:
        - "kibana_all_write"`

**Comment by Anthony7774** [comment]
The issue is still present in Opensearch version 1.2.0. The issue doesn't appear to be linked to wildcard, but regexp query itself.

**Comment by davidlago** [comment]
We are doing some "spring cleaning in the fall", and to make sure we focus our energies on the right issues and we get a better picture of the state of the repo, we are closing all issues that we are carrying over from the ODFE era (ODFE is no longer supported/maintained, see post [here](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/)). 

If you believe this issue should still be considered for current versions of OpenSearch, apologies! Please let us know by re-opening it.

Thanks!
