### ISSUE TITLE
OpenID Auth: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by QuingKhaos** [opensearch-project/security#1056]
| Q | A
| --- | ---
| Bug? | y
| New Feature? | n
| Related issues | #21 
| Version used | `amazon/opendistro-for-elasticsearch:1.13.0`

#### Actual Behavior

Configuring OpenID authentication with Keycloak as test IdP. The root CA of Keycloak server certificate is configured as `pemtrustedcas_filepath`.

Still on trying to authenticate with Kibana, it throws an `unable to find valid certification path to requested target` exception:

```
argos-insights-es1 | [2021-02-25T10:00:50,687][INFO ][c.a.d.a.h.j.k.JwtVerifier] [es1] Escaped Key ID from JWT Token
argos-insights-es1 | [2021-02-25T10:00:50,687][INFO ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [es1] Performing refresh 4
argos-insights-es1 | [2021-02-25T10:00:50,700][INFO ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [es1] com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Authentication backend failed
argos-insights-es1 | [2021-02-25T10:00:50,700][WARN ][c.a.o.s.a.BackendRegistry] [es1] Authentication finally failed for null from 192.168.144.2:45528
argos-insights-es1 | [2021-02-25T10:00:50,700][WARN ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [es1] KeySetProvider threw error
argos-insights-es1 | com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://keycloak:8443/auth/realms/insights/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
argos-insights-es1 | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:149) ~[opendistro_security-1.13.0.0.jar:1.13.0.0]
argos-insights-es1 | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:70) ~[opendistro_security-1.13.0.0.jar:1.13.0.0]
argos-insights-es1 | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:214) [opendistro_security-1.13.0.0.jar:1.13.0.0]
argos-insights-es1 | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
argos-insights-es1 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
argos-insights-es1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
argos-insights-es1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
argos-insights-es1 | 	at java.lang.Thread.run(Thread.java:832) [?:?]
argos-insights-es1 | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
argos-insights-es1 | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
argos-insights-es1 | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
argos-insights-es1 | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
argos-insights-es1 | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:122) ~[opendistro_security-1.13.0.0.jar:1.13.0.0]
argos-insights-es1 | 	... 7 more
```

It doesn't make any difference if I configure `pemtrustedcas_filepath` with a relative path or an absolute path`. Additionally using `pemtrustedcas_content` shows the same behaviour.

#### Expected Behavior

With the right root CA configured in `pemtrustedcas_filepath` it should connect to the OpenID connect url to retrieve the metadata.

#### Steps to Reproduce

Given the following configuration:

```yaml
# securityconfig/config.yml

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://keycloak:8443/auth/realms/insights/.well-known/openid-configuration
            enable_ssl: true
            verify_hostnames: true
            pemtrustedcas_filepath: root-ca.crt
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: clientcert
          challenge: false
          config:
            username_attribute: cn
        authentication_backend:
          type: noop
```

```yaml
# kibana.yml

opendistro_security.auth.type: "openid"
opendistro_security.openid.root_ca: "config/root-ca.crt"
opendistro_security.openid.connect_url: "https://keycloak:8443/auth/realms/insights/.well-known/openid-configuration"
opendistro_security.openid.client_id: "kibana-sso"
opendistro_security.openid.client_secret: "******************"
opendistro_security.openid.scope: "openid username roles"
opendistro_security.openid.base_redirect_url: "https://kibana:5601"
```

1. Use [`step ca init`](https://smallstep.com/docs/step-cli/reference/ca/init) to initialize a testing CA.
2. Use `step ca root -f root-ca.crt` to get the root CA file.
3. Use the following to generate the Keycloak certificate and private key.
  ```bash
  step ca certificate -f "keycloak" "argos-insights-keycloak.crt" "argos-insights-keycloak.key"
  step crypto key format -f --no-password --insecure --pem --pkcs8 --out "argos-insights-keycloak.key" "argos-insights-keycloak.key"
  ```
4. Verifify the OpenID Connect url with curl in the elasticsearch container:
  ```bash
  curl -v -I https://keycloak:8443/auth/realms/insights/.well-known/openid-configuration --cacert config/root-ca.crt
  ```

The [safe, and sane step-ca defaults](https://smallstep.com/docs/step-ca/certificate-authority-server-production#sane-cryptographic-defaults) generates ECC root, intermediate and leaf certificates. In the supplied `root-ca.crt` only the root CA is supplied. Keycloak delivers the server and intermediate certificate in it's response, as it should be configured and tested with curl to resolve the PKIX path.

Additionally check with the `step-cli`:

```bash
step certificate inspect --bundle --roots config/root-ca.crt https://keycloak:8443/auth/realms/insights/.well-known/openid-configuration
```

**Comment by romanganchin** [comment]
@QuingKhaos The docs seem to be wrong: https://github.com/opendistro-for-elasticsearch/security/issues/419

Try: 
`         config:
            subject_key: unique_name
            roles_key: group
            openid_connect_url: "https://url to adfs/.well-known/openid-configuration"
            openid_connect_idp.enable_ssl: true
            openid_connect_idp.verify_hostnames: true
            openid_connect_idp.pemtrustedcas_filepath: "/usr/share/elasticsearch/config/ca.crt"`

**Comment by coperni** [comment]
@QuingKhaos Did this work for you?

**Comment by andy840314** [comment]
Hi @QuingKhaos, thanks for opening this issue. Is this problem resolved after adding the prefix `openid_connect_idp` in the config?

**Comment by andy840314** [comment]
Tested on this issue. The prefix `openid_connect_idp` is needed and this is the corresponding line of code https://github.com/opensearch-project/security/blob/ea382b41d1132480139204d5bfead84f831900c4/src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java#L57
The documentation for [OpenID TLS section](https://opensearch.org/docs/security-plugin/configuration/openid-connect/#tls-settings) needs to be updated.

**Comment by andy840314** [comment]
Document updated.

**Comment by HaritzSaiz** [comment]
@andy840314 I don’t know if the issue is fixed. I've tried adding the `openid_connect_idp` prefix but I'm having the same error:
```
elastic_1            | [2021-08-07T08:21:34,763][WARN ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [elastic] KeySetProvider threw error
elastic_1            | com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://dev.lamassu.io:8443/auth/realms/lamassu/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:149) ~[opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:70) ~[opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:214) [opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
elastic_1            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
elastic_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
elastic_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
elastic_1            | 	at java.lang.Thread.run(Thread.java:832) [?:?]
elastic_1            | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
elastic_1            | 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:122) ~[opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	... 7 more
elastic_1            | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
elastic_1            | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
elastic_1            | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
elastic_1            | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
elastic_1            | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
elastic_1            | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:122) ~[opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	... 7 more
elastic_1            | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
elastic_1            | 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
elastic_1            | 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:?]
elastic_1            | 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
elastic_1            | 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[?:?]
elastic_1            | 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
elastic_1            | 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
elastic_1            | 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[?:?]
elastic_1            | 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) ~[?:?]
elastic_1            | 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[?:?]
elastic_1            | 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[?:?]
elastic_1            | 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:199) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:171) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
elastic_1            | 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
elastic_1            | 	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:122) ~[opendistro_security-1.13.1.0.jar:1.13.1.0]
elastic_1            | 	... 7 more
```

This is the security config file I'm using:  

```yml
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: "https://dev.lamassu.io:8443/auth/realms/lamassu/.well-known/openid-configuration"
            openid_connect_idp.enable_ssl: true
            openid_connect_idp.verify_hostnames: true
            openid_connect_idp.pemtrustedcas_filepath: "/usr/share/elasticsearch/config/keycloak.crt"
        authentication_backend:
          type: noop
```
I actually don't think the issue is related with the certificate itself as I'm able to successfully run a curl command within the docker container using the specified ca certificate path: 

```
curl https://dev.lamassu.io:8443/auth/realms/lamassu/.well-known/openid-configuration --cacert /usr/share/elasticsearch/config/keycloak.crt -I
```

```
HTTP/1.1 200 OK
Cache-Control: no-cache, must-revalidate, no-transform, no-store
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Referrer-Policy: no-referrer
Date: Sat, 07 Aug 2021 08:36:14 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Type: application/json
Content-Length: 3878
```
FYI: I'm using `amazon/opendistro-for-elasticsearch:1.13.2` docker image

**Comment by HaritzSaiz** [comment]
I finally got it working. Even if I changed the config file, the new configuration was not being used. I had to reload the configuration by running the `securityadmin.sh` command as described here: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/security-admin/
