### ISSUE TITLE
`unknown setting [opensearch_security.*`

### ISSUE THREAD

**Issue by denysvitali** [opensearch-project/security#1216]
**Description of the issue**

According to [this page](https://docs-beta.opensearch.org/docs/security/configuration/configuration/) (docs-beta), the `opensearchproject/opensearch:1.0.0-beta1` should accept the following options:

```
opensearch_security:
  dynamic:
    http:
      ...
    authc:
      ...
    authz:
      ...
```

Due to a missing renaming of the options (or due to the fact that we're using in the `opensearchproject/opensearch:1.0.0-beta1` image the OpenDistro security plugin), this results in the following OpenSearch error if one of those options (e.g: `opensearch_security.ssl.transport.keystore_filepath`) being used:

```
Caused by: java.lang.IllegalArgumentException: unknown setting [opensearch_security.ssl.transport.keystore_filepath] did you mean any of [opendistro_security.ssl.
transport.keystore_filepath, opendistro_security.ssl.transport.truststore_filepath, opendistro_security.ssl.transport.pemcert_filepath, opendistro_security.ssl.tr
ansport.keystore_alias, opendistro_security.ssl.transport.keystore_type, opendistro_security.ssl.transport.pemkey_filepath, opendistro_security.ssl.transport.keys
tore_password, opendistro_security.ssl.http.keystore_filepath, opendistro_security.ssl.transport.pemtrustedcas_filepath, opendistro_security.ssl.transport.keystor
e_keypassword]?
```

**To Reproduce**

```bash
docker run --rm -e 'opensearch_security.ssl.transport.keystore_filepath=/tmp/test.jks' opensearchproject/opensearch:1.0.0-beta1
```

**Expected behavior**

The option should be accepted and the user shouldn't use `opendistro_security` to work around the issue

**Plugins**

- `opensearch-security-1.0.1.0` ?

---

Unfortunately it's still unclear to me how the `opensearchproject/opensearch:1.0.0-beta1` image was created as I haven't found any CI related to the project and the image seems to have been pushed (manually?) by @peterzhuamazon

**Comment by nebulon42** [comment]
@dblock @vrozov The documentation still mentions that the root key for the config file is "opensearch_security" (see https://opensearch.org/docs/security-plugin/configuration/configuration/). The linked full example file on the other hand has "config" as the root key (see https://github.com/opensearch-project/security/blob/main/securityconfig/config.yml). According to the renaming PR #1176 it should be "plugin.security". Not sure which is correct now, will have to try this out. This is quite confusing. I'd recommend reopening this issue.

Another thing. Nowhere in the docs it is mentioned that you should have
```
_meta:
  type: "config"
  config_version: 2
```
in the file. It is only present in the sample file. However, OpenSearch complains about it:
```
[2021-08-30T16:23:47,952][ERROR][o.o.s.c.ConfigurationRepository] [logging] Cannot apply default config (this is maybe not an error!)
java.io.IOException: A version of 2 must have a _meta key for CONFIG
         at org.opensearch.security.securityconf.impl.SecurityDynamicConfiguration.validate(SecurityDynamicConfiguration.java:109) ~[opensearch-se>
         at org.opensearch.security.securityconf.impl.SecurityDynamicConfiguration.fromJson(SecurityDynamicConfiguration.java:89) ~[opensearch-sec>
         at org.opensearch.security.securityconf.impl.SecurityDynamicConfiguration.fromJson(SecurityDynamicConfiguration.java:74) ~[opensearch-sec>
         at org.opensearch.security.securityconf.impl.SecurityDynamicConfiguration.fromNode(SecurityDynamicConfiguration.java:123) ~[opensearch-se>
         at org.opensearch.security.support.ConfigHelper.fromYamlReader(ConfigHelper.java:142) ~[opensearch-security-1.0.0.0.jar:1.0.0.0]
         at org.opensearch.security.support.ConfigHelper.fromYamlFile(ConfigHelper.java:151) ~[opensearch-security-1.0.0.0.jar:1.0.0.0]
         at org.opensearch.security.support.ConfigHelper.uploadFile(ConfigHelper.java:73) ~[opensearch-security-1.0.0.0.jar:1.0.0.0]
         at org.opensearch.security.support.ConfigHelper.uploadFile(ConfigHelper.java:65) ~[opensearch-security-1.0.0.0.jar:1.0.0.0]
         at org.opensearch.security.configuration.ConfigurationRepository$1.run(ConfigurationRepository.java:137) [opensearch-security-1.0.0.0.jar>
         at java.lang.Thread.run(Thread.java:832) [?:?]
```
