### ISSUE TITLE
[BUG] Unable to disable security by following documentation

### ISSUE THREAD

**Issue by slovdahl** [opensearch-project/security#1249]
**Describe the bug**

According to https://docs-beta.opensearch.org/docs/security/configuration/disable/, it should be possible to disable security by setting `opensearch_security.disabled: true` in `opensearch.yml`. With 1.0.0-beta1, it was possible to use `docker run -p 9200:9200 -e "discovery.type=single-node" -e "opensearch_security.disabled=true" opensearchproject/opensearch:1.0.0-beta1` to start a local OpenSearch node for local testing without security. With 1.0.0-rc1, this doesn't work any more.

```
[2021-06-08T18:13:20,645][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [f4fbee7677c4] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [opensearch_security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
Caused by: java.lang.IllegalArgumentException: unknown setting [opensearch_security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:417) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalArgumentException: unknown setting [opensearch_security.disabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444)
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162)
	at org.opensearch.node.Node.<init>(Node.java:417)
	at org.opensearch.node.Node.<init>(Node.java:301)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
```

**To Reproduce**
1. Try to start a local OpenSearch container with `docker run -p 9200:9200 -e "discovery.type=single-node" -e "opensearch_security.disabled=true" opensearchproject/opensearch:1.0.0-rc1`. 

**Expected behavior**
The container is successfully started without security enabled.

**Plugins**
Nothing explicitly change. Output from container startup:
```
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-alerting]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-anomaly-detection]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-asynchronous-search]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-index-management]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-job-scheduler]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-knn]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-notebooks]
[2021-06-08T18:13:19,659][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-performance-analyzer]
[2021-06-08T18:13:19,660][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-reports-scheduler]
[2021-06-08T18:13:19,660][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-security]
[2021-06-08T18:13:19,660][INFO ][o.o.p.PluginsService     ] [f4fbee7677c4] loaded plugin [opensearch-sql]
```

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

A bit separate, but FWIW, having security enabled by default is a difference from the default Elasticsearch containers. We use the default Elasticsearch images in tests and local development and have used them without security up until now.

**Comment by dblock** [comment]
I've moved this to the security repo, definitely looks like a bug.

**Comment by cliu123** [comment]
@slovdahl Could you please try with `opendistro_security.disabled` instead of `opensearch_security.disabled`?

**Comment by andy840314** [comment]
For `1.0.0-beta1`, it should be `opendistro_security.disabled`. For `1.0.0.-rc1`, it should be `plugins.security.disabled`. There is no such settings for `opensearch_security.disabled`.

**Comment by dblock** [comment]
I think the doc should say "delete the <strike>opensearch_security</strike>plugins.security configuration entries from opensearch.yml"

**Comment by slovdahl** [comment]
> @slovdahl Could you please try with `opendistro_security.disabled` instead of `opensearch_security.disabled`?

Same problem:
```
$ docker run -p 9200:9200 -e "discovery.type=single-node" -e "opendistro_security.disabled=true" opensearchproject/opensearch:1.0.0-rc1

...

[2021-06-09T05:11:01,621][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [082447f12250] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [opendistro_security.disabled] did you mean [opendistro_security.audit.enable_rest]?
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
Caused by: java.lang.IllegalArgumentException: unknown setting [opendistro_security.disabled] did you mean [opendistro_security.audit.enable_rest]?
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:417) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0-rc1.jar:1.0.0-rc1]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalArgumentException: unknown setting [opendistro_security.disabled] did you mean [opendistro_security.audit.enable_rest]?
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:557)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:502)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:473)
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:444)
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:162)
	at org.opensearch.node.Node.<init>(Node.java:417)
	at org.opensearch.node.Node.<init>(Node.java:301)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
	at org.opensearch.cli.Command.main(Command.java:103)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
```

> For `1.0.0-beta1`, it should be `opendistro_security.disabled`. For `1.0.0.-rc1`, it should be `plugins.security.disabled`. There is no setting for `opensearch_security.disabled`.

Thank you! That did the trick. Is there a reference to this somewhere in the documentation? I couldn't find anything.

**Comment by perlun** [comment]
@cliu123 Thanks. I can also confirm that `docker run -p 9200:9200 -e "discovery.type=single-node" -e "plugins.security.disabled=true" opensearchproject/opensearch:1.0.0-rc1` does indeed work correctly. OpenSearch starts, with security disabled. :rocket: :bow: Thanks a lot for this!

### Sub-discussion about the changed security model

As for this comment from @slovdahl:

> A bit separate, but FWIW, having security enabled by default is a difference from the default Elasticsearch containers. We use the default Elasticsearch images in tests and local development and have used them without security up until now.

I do agree that this is a **big breaking change** in terms of drop-in compatibility for OpenSearch 1.0.0 vs ElasticSearch 7.10.

* Elasticsearch 7.10 listens on port 9200 with HTTP by default
* OpenSearch 1.0.0 listens on port 9200 **with HTTPS** by default, using a self-signed certificate, _and_ requires authentication

It would be interesting to hear if this has been discussed more in-depth within the project (please refer me to the GitHub issue(s) if this is indeed the case).

I suggest going with either one of the following approaches:

* Set `plugins.security.disabled=true` by default, making the security plugin be _opt-in_ as far as OpenSearch 1.0.0 is concerned (staying closer in spirit to the ES original semantics). The security plugin could then be enabled in a future release (like OS 2.0.0). _Or_, if this is not considered a good idea/has been discussed already:
* Make the docs be super-clear on this topic. It would perhaps make sense to have a sub-section somewhere saying "Switching back to Elasticsearch security semantics" or something.

And to make things clear: I'm not questioning the new security model _per se_. The default used by Elasticsearch has arguably been a bit odd. What I'm slightly questioning is the fact that this is being introduced in something that I had _perceived_ should be a drop-in replacement for existing Elasticsearch servers, with a minimum amount of fuss for our users. Perhaps this assumption is slightly incorrect?

**Comment by dblock** [comment]
> Thank you! That did the trick. Is there a reference to this somewhere in the documentation? I couldn't find anything.

Docs were fixed in https://github.com/opensearch-project/documentation-website/commit/c4cf6838bf8bfd6264a914d07fa71cb8a6c0a855 and I added https://github.com/opensearch-project/documentation-website/pull/48.

**Comment by dblock** [comment]
@perlun Thanks for your comments! 

Someone please correct me if I am wrong, but security is enabled by default in OpenDistro, so this isn't a breaking change. The equivalent of what you describe is the minimal Elasticsearch artifact, which is also going to also be available as OpenSearch, which won't know anything about the security plugin. There's a discussion on that [here](https://discuss.opendistrocommunity.dev/t/convergence-of-opensearch-opendistro-plugins/5625/33).

That said, security and reliability are both so critical that any artifacts without security built-in is 🤯 to me. I'd like to make security a module in some future (as opposed to a plugin, modules cannot be uninstalled) and effectively introduce a breaking change into the minimal artifact as well. We'll want to do that with all the appropriate discussions, deprecation and a major version increments as you rightfully point out.

**Comment by perlun** [comment]
@dblock Thanks for clearing things out. I do understand your (the project/AWS) perspective a bit better now. :+1: 

> The equivalent of what you describe is the minimal Elasticsearch artifact, which is also going to also be available as OpenSearch, which won't know anything about the security plugin. There's a discussion on that here.

Thanks, skimmed through that discussion a bit yesterday. I wonder if it makes sense to call both the "minimal Elasticsearch" and the "full, opinionated Elasticsearch + built-in plugins" as the same OpenSearch name though? I guess that's where the `-lite`, `-min`, `-core` etc suffix comes into picture, that definitely makes it clearer. Perhaps this is good enough for time being, given the future vision ("security included, cannot be disabled") you describe in a future major version

(I _do_ think that enforcing HTTPS even for dev environments is perhaps taking it a bit too far though, given the certificate hassles it involves, self-signed certificats et al. But that's a bit of a separate discussion. :slightly_smiling_face:)

Looking at https://hub.docker.com/r/opensearchproject/opensearch, I get the impression that we don't have a Docker image with the "bare", minimal OpenSearch (without security/etc) available yet. Looking forward to see it happen at some point. :pray:

**Comment by dblock** [comment]
Thanks for your feedback @perlun! The team had decided to call the product "OpenSearch" and "OpenSearch Dashboards". It's definitely confusing that opensearch-project/OpenSearch is just the min engine, but I learned to live with the mental model of OpenSearch (the product with all the plugins) and OpenSearch (the server engine) being two different things 🤣

**Comment by cliu123** [comment]
Closing the issue since the documentation has been corected.
