### ISSUE TITLE
[BUG] Certificate pem loader cannot tolerate duplicate certificates in chain

### ISSUE THREAD

**Issue by nneul** [opensearch-project/security#1431]
**Describe the bug**

The current code will reject a PEM certificate file if it has any duplicate certificates in it. (Such as if you had a config script that doubled the self signed cert as "cert + chain" when you didn't have an upstream cert.)

This can be considered a configuration error on user part, but would be nice if it would tolerate the situation instead of outright rejecting the "chain" without a clear explanation/error.

**To Reproduce**
1. Set up a self signed cert installation
2. Duplicate the cert in plugins.security.ssl.http.pemcert_filepath  - i.e. list the single certificate twice (such as if you were populating with certificate plus chain, but in this case, it was just the cert since it is it's own chain)
3. Attempt to start opensearch

**Expected behavior**
Normal startup, possibly with a warning about ignoring duplicate certificate in chain

**Plugins**
Security plugin

**Screenshots**

```
2021-08-26T22:18:38,465Z [ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [VDS]uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:186) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140) ~[opensearch-cli-1.0.0.jar:1.0.0]
	at org.opensearch.cli.Command.main(Command.java:103) ~[opensearch-cli-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105) ~[opensearch-1.0.0.jar:1.0.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:735) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:671) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0.jar:1.0.0]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:726) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:671) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0.jar:1.0.0]
	... 6 more
Caused by: org.opensearch.OpenSearchSecurityException: Error while initializing http SSL layer from PEM: javax.net.ssl.SSLException: failed to initialize the server-side SSL context
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initHttpSSLConfig(DefaultSecurityKeyStore.java:527) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:254) ~[?:?]
	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:169) ~[?:?]
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:249) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:726) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:671) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:492) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:181) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:357) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.node.Node.<init>(Node.java:301) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:240) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:406) ~[opensearch-1.0.0.jar:1.0.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.0.0.jar:1.0.0]
	... 6 more
```

**Host/Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20

**Additional context**

In my case, this was clearly a bad configuration/script populating these keys in the 'self signed cert' case where I was generating a file that had it twice - so easy fix -- but was really hard to tell what it was complaining about above, and it would be nice if it didn't just reject it to begin with.

**Comment by CEHENKLE** [comment]
Transferring to the security team.  please let me (@) if this is the wrong location.  Thanks!

**Comment by davidlago** [comment]
Thanks @nneul. I agree that at the very least we should have a more helpful error message here.

**Comment by scrawfor99** [comment]
[Triage] At this time Security has no plans to implement this feature at it seems likely to increase user error through deployment vulnerability. Please open a new issue if you wish to further discuss this topic. Thank you.
