### ISSUE TITLE
[BUG] Trace logging for OIDC

### ISSUE THREAD

**Issue by jamesdboone** [opensearch-project/security#1452]
Can't turn on trace logging for OIDC

Followed directions in troubleshooting to enable trace logging, but don't see any additional logs:
https://opensearch.org/docs/troubleshoot/openid-connect/

Added two lines to log4j2.properties in opensearch master pod (docker image opensearchproject/opensearch:1.0.0)
logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
logger.plugins.security.level = trace

No DEBUG logs were found on restart or during OIDC login attempt, got a stack dump.

```
Exception in thread "main" org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger plugins
        at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createLogger(PropertiesConfigurationBuilder.java:256)
        at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:178)
        at org.opensearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:229)
        at org.opensearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:197)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:239)
        at org.opensearch.common.logging.LogConfigurator$3.visitFile(LogConfigurator.java:237)
        at org.opensearch.common.logging.LogConfigurator$3.visitFile(LogConfigurator.java:233)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
        at org.opensearch.common.logging.LogConfigurator.configure(LogConfigurator.java:233)
        at org.opensearch.common.logging.LogConfigurator.configure(LogConfigurator.java:142)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:367)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:173)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.Command.main(Command.java:103)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:139)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:105)
```

**Expected behavior**
To find some DEBUG logs pertaining to OIDC login                 

**OpenSearch Version**
docker image opensearchproject/opensearch:1.0.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**
Default plugins are enabled, but have also enabled openid configuration.

Running on CentOS7.
Using Chrome, Version 92.0.4515.159

**Comment by peterzhuamazon** [comment]
Moved to security repo per @kavilla request.

**Comment by courtland** [comment]
I'm having the same problem - can't seem to get any OIDC-related logging out of the security plugin, and I'm not able to get it to work in general after following the documentation.

`logger.plugins...` causes an exception.

It seems like there may be a lingering bug/issue based on this thread, but the github links are dead/moved?
https://discuss.opendistrocommunity.dev/t/kibana-openid-connect-does-not-redirect-to-idp-identityserver4/4428/8

**Comment by wkruse** [comment]
Same here, would be awesome, if https://opensearch.org/docs/latest/troubleshoot/openid-connect/#set-log-level-to-debug could be fixed. It is a bit difficult to troubleshoot, when troubleshooting guide is broken. I am running into perpetual redirects issue with OIDC and would like to find out, why authentication fails in OpenSearch Dashboards.

**Comment by sdwerwed** [comment]
Yes it should be fixed in docs, it took me some time to understand how to enable the debug logs. In my case the redirections were due to large cookies (6KB), reducing the data send from OIDC provider helped, this article might  help https://www.linkedin.com/pulse/integrate-opensearch-azure-active-directory-dimitris-p-/

**Comment by wkruse** [comment]
@sdwerwed Thank you for the hint! In my case the root cause was running the `securityadmin.sh`, that overwrote the `config.yml` with default, that broke authentication.

**Comment by scrawfor99** [comment]
[Triage] Appears to be resolved through documentation change. Please open a new issue if there is further comments on this topic.
