### ISSUE TITLE
SSO not working with self-signed certificate

### ISSUE THREAD

**Issue by damobrisbane** [opensearch-project/security#1575]
**Describe the bug**
When trying to login to Opensearch Dashboards, dashboard is not loading, with an "The page isnt working, <kibana/os-dash>.internal.lan redirected too many times" error. Using truststore configured in Opensearch.yml. 

When the truststore is provided as runtime parameter (not an Opensearch.yml ssl configuration), SSO from OS-Dash to Opensearch works as expected.

**To Reproduce**
1. Set up a truststore, truststore.jks - with the local root and intermediate CA's in it. 
1. Reference truststore.jks in the plugins.security.ssl.transport.truststore_filepath and plugins.security.ssl.http.truststore_filepath Opensearch.yml configuration.
2. Attempt SSO from Opensearch Dashboards; redirect URL from OS-Dash to SSO (keycloak) is ok; do a Keycloak login, the connect provider calls back Opensearch using the redirect url that has been set up in OS-Dash; the OIDC role and profile is ok.
3. The getting a continuous stream of console log messages in OS-Dash:

```
log   [11:10:16.305] [error][data][opensearch] [ConnectionError]: connect ECONNREFUSED ossearch.internal.lan:9200
log   [11:10:16.728] [error][data][opensearch] [ConnectionError]: connect ECONNREFUSED ossearch.internal.lan:9200
...
```

**Expected behavior**
With a valid redirect url, JWT response with valid key, Opensearch can run [keybyoidc] JwtVerifier on the key returned in the JWT token.

**Plugins**
Unmodified Opensearch 1.2.0 docker install, apart from configuration files.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Gentoo
 - Version latest

**Additional context**

NOTE 1: Error in the Opensearch

```
[2022-01-15T11:06:31,459][DEBUG][c.a.d.a.h.j.k.SelfRefreshingKeySet] [ossearch.internal.lan] performRefresh(pNYNaCIKS5HmZcc8zs-TMtjPnC_cY04BVbJ5amioNhI)
[2022-01-15T11:06:31,459][INFO ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [ossearch.internal.lan] Performing refresh 1
[2022-01-15T11:06:31,614][INFO ][c.a.d.a.h.j.AbstractHTTPJwtAuthenticator] [ossearch.internal.lan] com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Authentication backend failed
[2022-01-15T11:06:31,614][WARN ][o.o.s.h.HTTPBasicAuthenticator] [ossearch.internal.lan] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2022-01-15T11:06:31,615][WARN ][o.o.s.a.BackendRegistry  ] [ossearch.internal.lan] Authentication finally failed for null from 10.0.5.8:45846
[2022-01-15T11:06:31,614][WARN ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [ossearch.internal.lan] KeySetProvider threw error
com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://sso.internal.lan/auth/realms/master/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:149) ~[opensearch-security-1.2.0.0.jar:1.2.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:70) ~[opensearch-security-1.2.0.0.jar:1.2.0.0]
	at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:214) [opensearch-security-1.2.0.0.jar:1.2.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

NOTE 2: verifying truststore on the broken instance (the one with above error); mounting SSLPoke and using truststore.jks:

```
 $> docker exec -it es /bin/bash -c 'java -Djavax.net.ssl.trustStore=/usr/share/opensearch/config/truststore.jks -jar /tmp/utils/SSLPoke-1.0.jar "sso.internal.lan" 9200'
Successfully connected
 $> 

```

NOTE 3: Successful SSO, only change being introduction of javax.net.ssl.trustStore in JAVA OPTS:

```
docker run  -e OPENSEARCH_JAVA_OPTS="-Djavax.net.ssl.trustStore=/usr/share/opensearch/config/truststore.jks" opensearchproject/opensearch:1.2.0
```

**Comment by pawelw1** [comment]
@damobrisbane this doesn't look like a bug but security plugin misconfiguration. Could you open a new case in the OpenSearch Forum (https://discuss.opendistrocommunity.dev/c/security/3)?

Please share the forum case link here.

**Comment by damobrisbane** [comment]
Thanks @pawelw1 - https://discuss.opendistrocommunity.dev/t/os-dashboards-login-redirecting-when-using-keycloak-and-self-signed-certs/8349

**Comment by davidlago** [comment]
Thanks @pawelw1 and @damobrisbane . Closing this in favor of the forum post linked.
