### ISSUE TITLE
[BUG] Security plugin installation fails locally

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/security#1633]
**Describe the bug**
Local installation of security plugin fails as plugin descriptor file contains "-SNAPSHOT" under `opensearch.version`.

**To Reproduce**
1. Build artifacts for security plugin
```
./gradlew clean assemble
```
2. Extract the generated distribution zip under `build/distributions/opensearch-security-1.3.0.0.*.zip`
3. Check the value for the attribute `opensearch.version` under `plugin-descriptor.properties` file

**Expected behavior**
As per [this](https://github.com/opensearch-project/opensearch-build/issues/359) issue - Opensearch doesn't support installation of plugins with "-SNAPSHOT" under version

**Comment by cliu123** [comment]
I've reproduced the issue.
```
Exception in thread "main" java.lang.IllegalArgumentException: illegal version format - snapshot labels are not supported
	at org.opensearch.Version.fromStringSlow(Version.java:201)
	at org.opensearch.Version.fromString(Version.java:196)
	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:252)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:799)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
