### ISSUE TITLE
Add support for build version qualifiers.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/security#1676]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1632, add support for `-Dbuild.version_qualifier=`. 

The distribution build process now supports passing additional optional qualifiers other than the 3 digit versions, e.g. `2.0.0-alpha1`. Add the ability to pass additional qualifier to build scripts, and generate artifacts with a version that includes the qualifier.

**Comment by cliu123** [comment]
Looks like OpenSearch core doesn't accept plugin version with version_qualifier. Plugin installation failed: https://github.com/opensearch-project/security/runs/5797837160?check_suite_focus=true
```
2022-04-02T05:49:53.3391925Z -> Installing file:///docker-host/security-plugin.zip
2022-04-02T05:49:53.3426933Z ##[error]Exception in thread "main" java.lang.IllegalArgumentException: the version needs to contain major, minor, and revision, and optionally the build: 2.0.0.0-alpha1
2022-04-02T05:49:53.3428210Z 	at org.opensearch.Version.fromString(Version.java:186)
2022-04-02T05:49:53.3428625Z 	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:222)
2022-04-02T05:49:53.3429203Z 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
2022-04-02T05:49:53.3429760Z 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
2022-04-02T05:49:53.3430273Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
2022-04-02T05:49:53.3430780Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
2022-04-02T05:49:53.3431282Z 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
2022-04-02T05:49:53.3431744Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-04-02T05:49:53.3432163Z 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
2022-04-02T05:49:53.3432587Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-04-02T05:49:53.3432972Z 	at org.opensearch.cli.Command.main(Command.java:101)
2022-04-02T05:49:53.3433771Z 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Comment by peterzhuamazon** [comment]
> Looks like OpenSearch core doesn't accept plugin version with version_qualifier. Plugin installation failed: https://github.com/opensearch-project/security/runs/5797837160?check_suite_focus=true
> 
> ```
> 2022-04-02T05:49:53.3391925Z -> Installing file:///docker-host/security-plugin.zip
> 2022-04-02T05:49:53.3426933Z ##[error]Exception in thread "main" java.lang.IllegalArgumentException: the version needs to contain major, minor, and revision, and optionally the build: 2.0.0.0-alpha1
> 2022-04-02T05:49:53.3428210Z 	at org.opensearch.Version.fromString(Version.java:186)
> 2022-04-02T05:49:53.3428625Z 	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:222)
> 2022-04-02T05:49:53.3429203Z 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
> 2022-04-02T05:49:53.3429760Z 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
> 2022-04-02T05:49:53.3430273Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
> 2022-04-02T05:49:53.3430780Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
> 2022-04-02T05:49:53.3431282Z 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
> 2022-04-02T05:49:53.3431744Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
> 2022-04-02T05:49:53.3432163Z 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
> 2022-04-02T05:49:53.3432587Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
> 2022-04-02T05:49:53.3432972Z 	at org.opensearch.cli.Command.main(Command.java:101)
> 2022-04-02T05:49:53.3433771Z 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
> ```

Synced up with @cliu123 on this as they are pulling the wrong artifacts which is not 2.0.0-alpha1, but 2.0.0.
