### ISSUE TITLE
[BUG] Plugin integTest against fgac cluster fails with SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/security#1771]
**What is the bug?**
Running test against a security enabled cluster fails with following exception.
This problem happens if using **Java 11** to run the test. After changing to Java 17 or 14, tests can be run successfully.

Want to confirm if this would bring any risk to our OS 2.0 rc1 release.

<details>

<summary>error trace</summary>

```
org.opensearch.indexmanagement.indexstatemanagement.action.ShrinkActionIT > test shrink with replicas FAILED
    java.io.IOException: peer not authenticated
        at __randomizedtesting.SeedInfo.seed([CE041C73B7D59E9A:64B42D7B64B45A69]:0)
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:927)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:307)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at org.opensearch.test.rest.OpenSearchRestTestCase.ensureNoInitializingShards(OpenSearchRestTestCase.java:956)
        at org.opensearch.test.rest.OpenSearchRestTestCase.cleanUpCluster(OpenSearchRestTestCase.java:356)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
            at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:516)
            at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:205)
            at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188)
            at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:360)
            at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:523)
            at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
            at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
            at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
            at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
            ... 1 more
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.indexstatemanagement.action.ShrinkActionIT.test shrink with replicas" -Dtests.seed=CE041C73B7D59E9A -Dtests.security.manager=false -Dtests.locale=vi-VN -Dtests.timezone=Australia/Victoria -Druntime.java=11
```

</details>

**How can one reproduce the bug?**

1. Using staging 2.0.0-rc1 docker image to bring up a security enabled cluster, 

<details>
<summary>docker-compose.yml</summary>

```
version: '3'

services:
  opensearch-node1:
    image: opensearchstaging/opensearch:2.0.0-rc1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```
</details>

2. Pull down IM plugin repo, run IM test against the above cluster

```
./gradlew integTest -Dopensearch.version=2.0.0-rc1 -Dbuild.snapshot=false -Dtests.rest.cluster="localhost:9200" -Dtests.cluster="localhost:9200" -Dtests.clustername="opensearch-cluster" -Dhttps=true -Duser=admin -Dpassword=admin 
```

**Comment by peternied** [comment]
[Triage] @cliu123 could you look into this?

Briefly reviewing the callstacks involved, this is an error from the RestClient in use by the integration test failing to verify the peer certificates.  This seem unlikely to be an issue with the security plugin.

@bowenlan-amzn did you have any server error logs at the time of this failure?

**Comment by peternied** [comment]
I am actively looking into this issue

**Comment by peternied** [comment]
I was unable to reproduce this bug, note; I am unable to use the docker-compose setup and instead did the following:

#### Setup OpenSearch Instance:
```
wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-rc1/2611/linux/x64/tar/dist/opensearch/opensearch-2.0.0-rc1-linux-x64.tar.gz
tar -xvf opensearch-2.0.0-rc1-linux-x64.tar.gz
./opensearch-2.0.0-rc1/opensearch-tar-install.sh
```
_Note; while java 11 is called out in the bug description the docker-compose script isn't altering the jdk under use, its Temurin-17.0.2+8_

#### Get IndexManagement tests
```
<Open OpenSearch-Build repo>
git fetch origin
git checkout origin/main (Its **2c2e4e4**)
./test.sh integ-test manifests/2.0.0/opensearch-2.0.0-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-rc1/2611/linux/x64/tar --component index-management --keep
<Wait for `Running integration tests for index-management` to appear in the prompt>
ctrl+c to terminate the run
find the tmp path indexmanagement was placed in (/tmp/tmp5b0_lvho/index-management)
Navigate to that directory
Run `export JAVA11_HOME=~/jdk-11.0.14.1+1` so tests can pick up the right java runtime
Run `./gradlew ':integTest' --tests "org.opensearch.indexmanagement.indexstatemanagement.action.ShrinkActionIT.test shrink with replicas" -Dtests.seed=CE041C73B7D59E9A -Dtests.security.manager=false -Dtests.locale=vi-VN -Dtests.timezone=Australia/Victoria -Druntime.java=11` (From the text output error message, includes seeds and other test configuration at time of failure)
```
Tests passes, xmloutput:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.opensearch.indexmanagement.indexstatemanagement.action.ShrinkActionIT" tests="1" skipped="0" failures="0" errors="0" timestamp="2022-04-27T21:47:18" hostname="dev-dsk-petern-1e-d7e6bfc0.us-east-1.amazon.com" time="2.093">
  <properties/>
  <testcase name="test shrink with replicas" classname="org.opensearch.indexmanagement.indexstatemanagement.action.ShrinkActionIT" time="2.093"/>
  <system-out><![CDATA[[2022-04-28T07:47:18,708][INFO ][o.o.i.i.a.ShrinkActionIT ] [test shrink with replicas] before test
[2022-04-28T07:47:18,906][INFO ][o.o.i.i.a.ShrinkActionIT ] [test shrink with replicas] initializing REST clients against [http://[::1]:40785, http://127.0.0.1:35217]
[2022-04-28T07:47:20,776][INFO ][o.o.i.i.a.ShrinkActionIT ] [test shrink with replicas] after test
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```
