### ISSUE TITLE
[BUG] CI distribution build failed on security plugin for 1.3.2

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/security#1809]
**What is the bug?**
Our distribution build is currently failing because of a security issue. Here is the context:
```
+ cp ./build/distributions/opensearch-security-1.3.2.0.zip ./build/distributions/opensearch-security-1.3.2.0-securityadmin-standalone.zip ./build/distributions/opensearch-security-1.3.2.0.zip ./builds/plugins
cp: warning: source file './build/distributions/opensearch-security-1.3.2.0.zip' specified more than once
2022-04-29 17:08:51 INFO     Recording plugins artifact for security: plugins/opensearch-security-1.3.2.0.zip (from /tmp/tmp972_4s90/security/builds/plugins/opensearch-security-1.3.2.0.zip)
2022-04-29 17:08:51 INFO     Checked /tmp/tmp972_4s90/security/builds/plugins/opensearch-security-1.3.2.0.zip (1.3.2.0)
2022-04-29 17:08:51 INFO     Recording plugins artifact for security: plugins/opensearch-security-1.3.2.0-securityadmin-standalone.zip (from /tmp/tmp972_4s90/security/builds/plugins/opensearch-security-1.3.2.0-securityadmin-standalone.zip)
2022-04-29 17:08:51 ERROR    Error building security, retry with: ./build.sh manifests/1.3.2/opensearch-1.3.2.yml --component security
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 69, in main
    builder.export_artifacts(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 65, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/build_recorder.py", line 40, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/build_artifact_checks.py", line 42, in check
    instance.check(path)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/opensearch/build_artifact_check_plugin.py", line 20, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, f"Expected filename to include one of {self.target.compatible_component_versions}.")
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact opensearch-security-1.3.2.0-securityadmin-standalone.zip is invalid. Expected filename to include one of ['1.3.2.0'].
```

**How can one reproduce the bug?**
Run `./build.sh manifests/1.3.2/opensearch-1.3.2.yml --component security` 

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by cliu123** [comment]
@peternied 1.3.2 infra build pipeline fails. Looks like related to `security-admin-standalone` zip file. Can you take a look?

**Comment by peterzhuamazon** [comment]
We should consider remove it from 1.3 branch if not needed anymore.
Adding custom security script is not ideal consider @peternied just removed the custom script for 2.0.0 a while ago.
https://github.com/opensearch-project/opensearch-build/pull/1927

**Comment by peterzhuamazon** [comment]
Approve #1811 for now as this script only touch 1.3 branch.

**Comment by peternied** [comment]
https://github.com/opensearch-project/security/pull/1811 has been closed
