### ISSUE TITLE
[BUG] Getting exception while indexing document with user having role with document level security enabled

### ISSUE THREAD

**Issue by swapnilsvaidya** [opensearch-project/security#1892]
**What is the bug?**
A clear and concise description of the bug.
I have created a user which is mapped with role having document level security enabled.
If I try to index the document through Bulkrequest using this user I get following exception:

 [ElasticsearchException[Elasticsearch exception [type=security_exception, reason=_opendistro_security_dls_query does not match (SG 900D)]]]

In OpenSearch logs, following is the exception logged.
resolved: Resolved [aliases=[], allIndices=[test_index], types=[*], originalRequested=[test_index], remoteIndices=[]]
mode: ADAPTIVE
[2022-06-19T05:44:05,351][DEBUG][o.o.s.c.DlsQueryParser   ] [node-1] containsTermLookupQuery() returns false
queries: [{"term": { "pminstanceid.keyword": "instance1"}}]
[2022-06-19T05:44:05,352][DEBUG][o.o.s.c.DlsFlsValveImpl  ] [node-1] Doing lucene-level DLS because the query does not contain a TLQ
[2022-06-19T05:44:05,352][DEBUG][o.o.s.f.SecurityFilter   ] [node-1] Failed to apply filter. Task id: 224 (requests[1], index[test_index][0]). Action: indices:data/write/bulk[s]
org.opensearch.OpenSearchSecurityException: _opendistro_security_dls_query does not match (SG 900D)
	at org.opensearch.security.configuration.DlsFlsValveImpl.setDlsHeaders(DlsFlsValveImpl.java:390) ~[opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.configuration.DlsFlsValveImpl.invoke(DlsFlsValveImpl.java:157) ~[opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:320) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:157) [opensearch-security-2.0.1.0.jar:2.0.1.0]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:202) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:174) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:102) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.bulk.TransportBulkAction$BulkOperation.doRun(TransportBulkAction.java:632) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:774) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.action.bulk.TransportBulkAction$1$1.doRun(TransportBulkAction.java:321) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) [opensearch-2.0.1.jar:2.0.1]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.0.1.jar:2.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

After looking into the code, it seems DlsFlsValveImpl is trying to read the dls query related header from the request.
------Code snipper from DlsFlsValveImpl -----
if (threadContext.getHeader(ConfigConstants.OPENDISTRO_SECURITY_DLS_QUERY_HEADER) != null) {
                    Object deserializedDlsQueries = Base64Helper.deserializeObject(threadContext.getHeader(ConfigConstants.OPENDISTRO_SECURITY_DLS_QUERY_HEADER));
                    if (!dlsQueries.equals(deserializedDlsQueries)) {                        
                        throw new OpenSearchSecurityException(ConfigConstants.OPENDISTRO_SECURITY_DLS_QUERY_HEADER + " does not match (SG 900D)");
                    }
                }
----------------------------------------------
However I think this header should not come into picture while indexing the document.
This seems a bug.

**How can one reproduce the bug?**
Create a Role with DLS enabled, associate this role with user. Index the document using bulk request and using this user.
Verify bulkresponse

**What is the expected behavior?**
While indexing DLS should be ignored

**What is your host/environment?**
 - OS: [e.g. iOS] All OS
 - Plugins

**Do you have any screenshots?**
NA

**Do you have any additional context?**
NA

**Comment by swapnilsvaidya** [comment]
@peternied Hi Peter, Could you please confirm if you are looking into this issue?

**Comment by peternied** [comment]
Hi @swapnilsvaidya I am not currently looking into this issue, and it has been added to our work queue.  If you would like to create a pull request the maintainers and I would gladly review it.

**Comment by rursprung** [comment]
i haven't seen the corresponding comment in the OpenSearch Security documentation, but e.g. Search Guard explicitly declares that roles with DLS enabled mustn't have write access: https://docs.search-guard.com/latest/document-level-security#dls-and-write-access

i presume the same applies for OpenSearch Security and needs to be documented (and maybe enforced by a check in a new major release?)

**Comment by cliu123** [comment]
@opensearch-project/transfer-request This looks a documentation issue. Could you transfer to documentation repo? Thanks!

**Comment by rursprung** [comment]
@cliu123: seems that your transfer request hasn't happened yet. would it make sense to instead raise a new, well described, issue in the documentation repo and then close this one here with a reference to the new one?
