### ISSUE TITLE
plugins.security.ssl.http.enabled setting cannot be disabled on Rest layer as securityadmin.sh execution fails.

### ISSUE THREAD

**Issue by pratikshavyas** [opensearch-project/security#1952]
**What is the bug?**
With setting "plugins.security.ssl.http.enabled" as false, securityadmin.sh execution fails.

**How can one reproduce the bug?**
Disable TLS on Rest layer in Opensearch cluster by setting  "plugins.security.ssl.http.enabled" to false and then run securityadmin.sh script to initialize .opendistro_security index.

**What is the expected behavior?**
Securityadmin.sh must execute successfully without any errors.

**What is your host/environment?**
 - OpenSearch version: 2.1.0
 - OpenSearch-security plugin version: 2.1.0.0

**Do you have any screenshots?**
Error logs observed while running securityadmin.sh with TLS being disabled on Rest layer:
ERR: An unexpected IOException occured: Unrecognized SSL message, plaintext connection?
Trace:
java.io.IOException: Unrecognized SSL message, plaintext connection?
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:927)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:307)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:462)
        at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:159)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:557)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:275)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:321)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:523)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by cliu123** [comment]
@pratikshavyas Thanks for filing the issue!

**Comment by pratikshavyas** [comment]
Hi @cliu123 
Can you please share the plan on fixing this issue and when can we expect a solution?

**Comment by peternied** [comment]
@pratikshavyas This is very low on our internal backlog as we would always recommend clusters operate with TLS enabled.  We are happy to accept pull requests if you'd like this functionality to be added sooner.

**Comment by pratikshavyas** [comment]
We have a use case to use Opensearch with security for authorization and authentication and integrate with istio for handling TLS.
I have raised a ticket for the same on Opensearch discussion forum: https://forum.opensearch.org/t/integration-of-opensearch-security-with-istio/10283
Can you please provide some insight or recomment a way on how to integrate istio with Opensearch security.

**Comment by peternied** [comment]
Thanks for bringing up this use case, we will look into this

**Comment by peternied** [comment]
@pratikshavyas After considering this scenario, the security plugin's TLS system is used to authenticate the connection with the security plugin.  Without this authentication we cannot authorize the actions run by the security admin tool - a huge security risk if this were to be allowed.

**Comment by pratikshavyas** [comment]
Hi @peternied 
Does that mean the parameter plugins.security.ssl.http.enabled cannot be disabled at all? Has this been documented? If not, please do so and kindly share the link for our reference.

**Comment by peternied** [comment]
I've created an issue to document this is clearer language.
