### ISSUE TITLE
[IntegTest][Bug] security failed on no-security integ-test on 2.2.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/security#2015]
```
2022-08-09 22:14:26 ERROR    | security             | with-security        | FAIL  |    1 |
FAILURE: Build failed with an exception.

* What went wrong:
Task 'integTest' not found in root project 'opensearch-security'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

**Comment by peterzhuamazon** [comment]
New failure after using the main branch for testing:
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

REPRODUCE WITH: ./gradlew ':integTestRemote' --tests "org.opensearch.security.sanity.tests.SingleClusterSanityIT.testSecurityPluginInstallation" -Dtests.seed=FF26249F4BDD1D1C -Dtests.security.manager=false -Dtests.locale=ar-SY -Dtests.timezone=AET -Druntime.java=17


Suite: Test class org.opensearch.security.sanity.tests.SingleClusterSanityIT
  2> REPRODUCE WITH: ./gradlew ':integTestRemote' --tests "org.opensearch.security.sanity.tests.SingleClusterSanityIT.testSecurityPluginInstallation" -Dtests.seed=FF26249F4BDD1D1C -Dtests.security.manager=false -Dtests.locale=ar-SY -Dtests.timezone=AET -Druntime.java=17
  2> java.lang.AssertionError:
    Expected: iterable containing ["opensearch-security"]
         but: not matched: "opensearch-cross-cluster-replication"
        at __randomizedtesting.SeedInfo.seed([FF26249F4BDD1D1C:64C2A7413CF3574F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.opensearch.security.sanity.tests.SingleClusterSanityIT.verifyPluginInstallationOnAllNodes(SingleClusterSanityIT.java:47)
        at org.opensearch.security.sanity.tests.SingleClusterSanityIT.testSecurityPluginInstallation(SingleClusterSanityIT.java:35)
  2> NOTE: leaving temporary files on disk at: /tmp/tmphm8jxvo9/security/build/testrun/integTestRemote/temp/org.opensearch.security.sanity.tests.SingleClusterSanityIT_FF26249F4BDD1D1C-001
  2> NOTE: test params are: codec=Asserting(Lucene92): {}, docValues:{}, maxPointsInLeafNode=1014, maxMBSortInHeap=5.857046469067139, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-SY, timezone=AET
  2> NOTE: Linux 5.4.204-124.362.amzn2int.x86_64 amd64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=8,threads=1,free=385504728,total=536870912
  2> NOTE: All tests run in this JVM: [SingleClusterSanityIT]

1 test completed, 1 failed

=== Standard output of node `node{::integTestRemote-0}` ===

=== Standard error of node `node{::integTestRemote-0}` ===

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTestRemote'.
> There were failing tests. See the report at: file:///tmp/tmphm8jxvo9/security/build/reports/tests/integTestRemote/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
```
