### ISSUE TITLE
[BUG] Certificate expired blocking all tests cases in 1.0 branch.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2578]
**What is the bug?**
Seeing expired certificates when running tests against `1.0` builds [[link]](https://github.com/opensearch-project/security/actions/runs/4447793131/jobs/7887591232?pr=2330).  Note because of the number of messages that are output to the console you will see `Error: The log was not found. It may have been deleted based on retention settings.` in the GitHub Action, [StackOverflow Link](https://stackoverflow.com/questions/75812628/github-action-job-step-failed-with-error-the-log-was-not-found-message-inste/75812629#75812629).

<details>
<summary>From the stack trace

One of the certificates that the test uses has expired causing all of the test to fail when connecting to the cluster
`Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Feb 16 16:19:25 UTC 2022`

</summary>

```
2023-03-22T02:57:44.9976896Z javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2023-03-22T02:57:44.9978503Z 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
2023-03-22T02:57:44.9979327Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:325) ~[?:?]
2023-03-22T02:57:44.9980492Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:268) ~[?:?]
2023-03-22T02:57:44.9981098Z 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
2023-03-22T02:57:44.9981673Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340) ~[?:?]
2023-03-22T02:57:44.9982350Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1215) ~[?:?]
2023-03-22T02:57:44.9982994Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1158) ~[?:?]
2023-03-22T02:57:44.9983890Z 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[?:?]
2023-03-22T02:57:44.9984504Z 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:445) ~[?:?]
2023-03-22T02:57:44.9985148Z 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1260) ~[?:?]
2023-03-22T02:57:44.9985694Z 	at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1247) ~[?:?]
2023-03-22T02:57:44.9986294Z 	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
2023-03-22T02:57:44.9986798Z 	at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1192) ~[?:?]
2023-03-22T02:57:44.9987661Z 	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1557) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9988464Z 	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1571) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9989190Z 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1455) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9989952Z 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9990700Z 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329) [netty-handler-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9991619Z 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9992577Z 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9993453Z 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9994427Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9995480Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9996505Z 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9997477Z 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9998451Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:44.9999500Z 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0000514Z 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0001420Z 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0002280Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0003165Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0004049Z 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0004801Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0006129Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0007198Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.59.Final.jar:4.1.59.Final]
2023-03-22T02:57:45.0007744Z 	at java.lang.Thread.run(Thread.java:832) [?:?]
2023-03-22T02:57:45.0008313Z Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
2023-03-22T02:57:45.0009044Z 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369) ~[?:?]
2023-03-22T02:57:45.0009608Z 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263) ~[?:?]
2023-03-22T02:57:45.0010131Z 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
2023-03-22T02:57:45.0010645Z 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
2023-03-22T02:57:45.0011247Z 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2023-03-22T02:57:45.0011885Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318) ~[?:?]
2023-03-22T02:57:45.0012302Z 	... 31 more
2023-03-22T02:57:45.0012668Z Caused by: java.security.cert.CertPathValidatorException: validity check failed
2023-03-22T02:57:45.0013331Z 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135) ~[?:?]
2023-03-22T02:57:45.0014095Z 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:237) ~[?:?]
2023-03-22T02:57:45.0014794Z 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:145) ~[?:?]
2023-03-22T02:57:45.0015530Z 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84) ~[?:?]
2023-03-22T02:57:45.0016187Z 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309) ~[?:?]
2023-03-22T02:57:45.0016732Z 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364) ~[?:?]
2023-03-22T02:57:45.0017284Z 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263) ~[?:?]
2023-03-22T02:57:45.0017806Z 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
2023-03-22T02:57:45.0018336Z 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
2023-03-22T02:57:45.0018924Z 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2023-03-22T02:57:45.0019558Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318) ~[?:?]
2023-03-22T02:57:45.0020091Z 	... 31 more
2023-03-22T02:57:45.0020482Z Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Feb 16 16:19:25 UTC 2022
2023-03-22T02:57:45.0020999Z 	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277) ~[?:?]
2023-03-22T02:57:45.0021501Z 	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:673) ~[?:?]
2023-03-22T02:57:45.0022051Z 	at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190) ~[?:?]
2023-03-22T02:57:45.0022621Z 	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144) ~[?:?]
2023-03-22T02:57:45.0023558Z 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125) ~[?:?]
2023-03-22T02:57:45.0024339Z 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:237) ~[?:?]
2023-03-22T02:57:45.0025042Z 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:145) ~[?:?]
2023-03-22T02:57:45.0025762Z 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84) ~[?:?]
2023-03-22T02:57:45.0026418Z 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309) ~[?:?]
2023-03-22T02:57:45.0027063Z 	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364) ~[?:?]
2023-03-22T02:57:45.0027697Z 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263) ~[?:?]
2023-03-22T02:57:45.0028271Z 	at sun.security.validator.Validator.validate(Validator.java:264) ~[?:?]
2023-03-22T02:57:45.0028793Z 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285) ~[?:?]
2023-03-22T02:57:45.0029454Z 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[?:?]
2023-03-22T02:57:45.0030075Z 	at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318) ~[?:?]
2023-03-22T02:57:45.0030497Z 	... 31 more
```
</details>

The certificate should be updated so it doesn't expire in 100+ years to avoid this from happening again.

**Comment by cwperks** [comment]
Not sure if its the same issue, but one of my first PRs was against opendistro-1.13 and I had to update certs: https://github.com/opensearch-project/security/pull/1943

**Comment by scrawfor99** [comment]
[Triage] Hi @peternied, thank you for filing this issue. I know that you are working on looking at the backports for these two branches so I am leaving this unassigned.

**Comment by peternied** [comment]
This was fixed with the PR above that was merged
