### ISSUE TITLE
[BUG] OpenSearchException[No truststore configured for server certs]

### ISSUE THREAD

**Issue by Demon-DK** [opensearch-project/security#2934]
**What is your host/environment?**
 - OS: CentOS/Redhat 7.9
 - OpenSearch Version:  2.8.0
 - OpenSearch Security Version: 2.8.0.0
<br/>

**What is the bug?**
Opensearch does not work with trusted keystore configuration and throws the error `OpenSearchException: No truststore configured for server certs` at the start.
<br/>

**How can one reproduce the bug?**
Create typical Opensearch docker-compose container config and map certificates keystore and config:
```
...
volumes:
  - /apps/opensearch/ssl:/usr/share/opensearch/config/ssl:rw
  - /apps/opensearch/data:/usr/share/opensearch/data:rw
  - /apps/opensearch/logs:/usr/share/opensearch/logs:rw
  - /apps/opensearch/snapshots:/usr/share/opensearch/snapshots:rw
  - /apps/opensearch/configs/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
  - /apps/opensearch/configs/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
```

Then it is how the `/usr/share/opensearch/config/opensearch.yml` looks like:
```
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.keystore_type: JKS
plugins.security.ssl.http.keystore_filepath: ssl/ops-keystore.jks
plugins.security.ssl.http.keystore_password: changeit
plugins.security.ssl.http.truststore_type: JKS
plugins.security.ssl.http.truststore_filepath: ssl/ops-keystore.jks
plugins.security.ssl.http.truststore_password: changeit
# -----------------------------------------
plugins.security.ssl.transport.keystore_type: JKS
plugins.security.ssl.transport.keystore_filepath: ssl/ops-keystore.jks
plugins.security.ssl.transport.keystore_password: changeit
plugins.security.ssl.transport.truststore_type: JKS
plugins.security.ssl.transport.truststore_filepath: ssl/ops-keystore.jks
plugins.security.ssl.transport.truststore_password: changeit
plugins.security.ssl.transport.enforce_hostname_verification: false
# -----------------------------------------
plugins.security.authcz.admin_dn:
  - CN=ops-server
plugins.security.nodes_dn:
  - 'CN=ops-server'
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
# -----------------------------------------
cluster.routing.allocation.disk.threshold_enabled: false
opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.config.disabled_transport_categories: NONE
# -----------------------------------------
```
<br/>
<br/>

**Do you have any additional context?**
Finally you will get the following log with the exception:
```
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-2.8.0
Detected OpenSearch Security Version: 2.8.0.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
[2023-07-05T07:51:42,017][INFO ][o.o.n.Node               ] [opensearch] version[2.8.0], pid[34], build[tar/db90a415ff2fd428b4f7b3f800a51dc229287cb4/2023-06-03T06:24:25.112415503Z], OS[Linux/5.4.101-1.el7.elrepo.x86_64/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.7/17.0.7+7]
[2023-07-05T07:51:42,018][INFO ][o.o.n.Node               ] [opensearch] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]
[2023-07-05T07:51:42,019][INFO ][o.o.n.Node               ] [opensearch] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-10335516082585329633, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/config/opensearch-performance-analyzer/opensearch_security.policy, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, -Dopensearch.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Djava.net.preferIPv4Stack=true, -Des.transport.cname_in_publish_address=true, -XX:MaxDirectMemorySize=268435456, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2023-07-05T07:51:42,659][INFO ][o.o.s.s.t.SSLConfig      ] [opensearch] SSL dual mode is disabled
[2023-07-05T07:51:42,660][INFO ][o.o.s.OpenSearchSecurityPlugin] [opensearch] OpenSearch Config path is /usr/share/opensearch/config
[2023-07-05T07:51:42,827][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch] JVM supports TLSv1.3
[2023-07-05T07:51:42,829][INFO ][o.o.s.s.DefaultSecurityKeyStore] [opensearch] Config directory is /usr/share/opensearch/config/, from there the key- and truststore files are resolved relatively
[2023-07-05T07:51:42,833][INFO ][o.o.s.s.u.SSLCertificateHelper] [opensearch] No alias given, use the first one: 1
[2023-07-05T07:51:42,879][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.8.0.jar:2.8.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
        at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:791) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:454) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.8.0.jar:2.8.0]
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:782) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:454) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.8.0.jar:2.8.0]
        ... 6 more
Caused by: org.opensearch.OpenSearchSecurityException: Error while initializing transport SSL layer: OpenSearchException[No truststore configured for server certs]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:370) ~[?:?]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:256) ~[?:?]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:177) ~[?:?]
        at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]
        at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:266) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:782) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:454) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.8.0.jar:2.8.0]
        ... 6 more
Caused by: org.opensearch.OpenSearchException: No truststore configured for server certs
        at org.opensearch.security.ssl.util.CertFromTruststore.validate(CertFromTruststore.java:72) ~[?:?]
        at org.opensearch.security.ssl.util.CertFromTruststore.<init>(CertFromTruststore.java:54) ~[?:?]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:354) ~[?:?]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:256) ~[?:?]
        at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:177) ~[?:?]
        at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]
        at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:266) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:782) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:454) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.node.Node.<init>(Node.java:381) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.8.0.jar:2.8.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.8.0.jar:2.8.0]
```

**Comment by Demon-DK** [comment]
Since it is not clear from the log where is the root cause it was:
<br/>

1) Tried both `pkcs#8` and `pkcs#1` type of keys, with `3DES` encryption and without it
<br/>

2) Keystore where created by two approaches as well, with rootCA included and without it:
```
openssl pkcs12 -export -in ops-server.pem -inkey ops-server-key.pem -out ops-keystore.p12
openssl pkcs12 -export -in ops-server.pem -inkey ops-server-key.pem -certfile opsCA-crt.pem -out ops-keystore.p12
```


3) And both keystores where also converted to `JKS`

```
keytool -importkeystore                              \
  -srcstoretype PKCS12                               \
  -deststoretype JKS                                 \
  -srckeystore /apps/opensearch/ssl/ops-keystore.p12 \
  -destkeystore /apps/opensearch/ssl/ops-keystore.jks
```

**Comment by scrawfor99** [comment]
[Triage] Hi @Demon-DK, thank you for filing this issue. It looks like this may be related to the certificate configuration you are using. Someone will take a look at this shortly and update with their findings.

**Comment by Demon-DK** [comment]
Issue identified and was resolved !!!
-------------------
<br/>

So, eventually a lot of clues says that this is omething wrong with my certificates.
Therefore I did manual comparison of all essential settings of `root-CA` and `server/node` **pem** certificates between my certs and OpenSearch self-signed server/node certificate are generated by 'install_demo_configuration.sh' script.

As a result I found one particular setting `Authority Key Identifier ...` which was different against my certificate (_watch brief certificates output below_).
Adding this setting to my certificate solved the problem.


There is maybe only one note to Opensearch team:
- There are no a tip in the documentation about some particular mandatory requirements to certificate format
- Logging of this issue quite poor and gives no clues where exactly the issue
<br/>

**My self-signed server/node certificate**
```
X509v3 extensions:
    X509v3 Basic Constraints:
        CA:FALSE
    X509v3 Key Usage:
        Digital Signature, Non Repudiation, Key Encipherment
    X509v3 Extended Key Usage:
        TLS Web Server Authentication, TLS Web Client Authentication
    X509v3 Subject Alternative Name:
              ............
```
<br/>

**OpenSearch self-signed server/node certificate**
```
X509v3 extensions:
    X509v3 Basic Constraints:
        CA:FALSE
    X509v3 Key Usage:
        Digital Signature, Non Repudiation, Key Encipherment
    X509v3 Extended Key Usage:
        TLS Web Server Authentication, TLS Web Client Authentication
|-------------------------------------------------------------------|
|    X509v3 Authority Key Identifier:                               |
|        DirName:/DC=com/DC=example/O=Example Com Inc .....         |
|-------------------------------------------------------------------|
    X509v3 Subject Alternative Name:
              ............
```

**Comment by peternied** [comment]
@Demon-DK You mention that the documentation didn't help you out in this scenario - do you have thoughts on how the [[certificate documentation]](https://opensearch.org/docs/latest/security/configuration/tls/) could be improved, want to open an [[issue]](https://github.com/opensearch-project/documentation-website/issues/new?assignees=&labels=untriaged&projects=&template=issue_template.md&title=%5BDOC%5D)?
