### ISSUE TITLE
[BUG] DLS evaluation mode cannot be adapted on opensearch.yml

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/security#3794]
**What is the bug?**
OpenSearch documentation on [DLS](https://opensearch.org/docs/latest/security/access-control/document-level-security/#dls-evaluation-modes) states that one can tweak the DLS evaluation mode to `filter-level`, `lucene-level`, or `adaptive-level` on opensearch.yml

However, setting this on opensearch.yml produces an error, with the `plugins.security.dls.mode` setting not being recognised:
```
[2023-12-04T13:39:14,659][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node1] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [plugins.security.dls.mode] did you mean any of [plugins.security.disabled, plugins.security.audit.type, plugins.security.ssl_only, plugins.security.cert.oid]?
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.11.1.jar:2.11.1]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.11.1.jar:2.11.1]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.11.1.jar:2.11.1]
```

**How can one reproduce the bug?**
1. Add `plugins.security.dls.mode: filter-level` on opensearch.yml
2. Restart the node

**What is the expected behavior?**
Either the DLS mode to be adapted accordingly, or the relevant documentation should be removed.

**What is your host/environment?**
 - OpenSearch v2.11.1

**Comment by cwperks** [comment]
[Triage] @spapadop Thank you for filing this issue.

**Comment by dgsardina** [comment]
Is there any update to this matter? Is this setting valid? I just tried to configure it using the API (see below) and got an error.
```json
PUT _cluster/settings
{
  "persistent" : {
    "plugins.security.dls.mode": "filter-level"
  }
}
```

```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "persistent setting [plugins.security.dls.mode], not recognized"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "persistent setting [plugins.security.dls.mode], not recognized"
  },
  "status": 400
}
```
