### ISSUE TITLE
[Test] Test cases are failing on main branch.

### ISSUE THREAD

**Issue by pratiktonage** [opensearch-project/security#3928]
Hi Team,
I am working on validating OpenSearch security plugin on top of tree.
Encountered an error while testing the project with ./gradlew test command.
Test cases are failing with the following error:
Full logs for the same:

```> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :copyPluginPropertiesTemplate UP-TO-DATE
> Task :pluginProperties UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
> Task :copyExtraTestResources UP-TO-DATE
> Task :test

org.opensearch.security.HttpIntegrationTests > testHTTPSCompression FAILED
    java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
        at __randomizedtesting.SeedInfo.seed([7BF73791BE9626EB:A7667941C3763408]:0)
        at org.opensearch.security.test.helper.rest.RestHelper.executeRequest(RestHelper.java:289)
        at org.opensearch.security.test.helper.rest.RestHelper.executeGetRequest(RestHelper.java:176)
        at org.opensearch.security.HttpIntegrationTests.testHTTPSCompression(HttpIntegrationTests.java:452)

        Caused by:
        javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
            at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:153)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
            at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
            at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
            at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
            at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
            at java.base/java.lang.Thread.run(Thread.java:840)

org.opensearch.security.InitializationIntegrationTests > testEnsureInitViaRestDoesWork FAILED
    java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
        at __randomizedtesting.SeedInfo.seed([7BF73791BE9626EB:57968C66C52778ED]:0)
        at org.opensearch.security.test.helper.rest.RestHelper.executeRequest(RestHelper.java:289)
        at org.opensearch.security.test.helper.rest.RestHelper.executePutRequest(RestHelper.java:199)
        at org.opensearch.security.InitializationIntegrationTests.testEnsureInitViaRestDoesWork(InitializationIntegrationTests.java:83)

        Caused by:
        javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
            at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:153)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
            at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
            at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
            at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
            at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
            at java.base/java.lang.Thread.run(Thread.java:840)

org.opensearch.security.IndexIntegrationTests > testIndexResolveInvalidIndexName FAILED
    java.lang.RuntimeException: Could not start all nodes BindHttpException[Failed to bind to 127.0.0.1:8743]; nested: BindException[Address already in use];
        at __randomizedtesting.SeedInfo.seed([7BF73791BE9626EB:911D081CB718F8E0]:0)
        at org.opensearch.security.test.helper.cluster.ClusterHelper.startCluster(ClusterHelper.java:273)
        at org.opensearch.security.test.helper.cluster.ClusterHelper.startCluster(ClusterHelper.java:124)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:119)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:83)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:69)
        at org.opensearch.security.IndexIntegrationTests.testIndexResolveInvalidIndexName(IndexIntegrationTests.java:633)

        Caused by:
        BindHttpException[Failed to bind to 127.0.0.1:8743]; nested: BindException[Address already in use];
            at app//org.opensearch.http.AbstractHttpServerTransport.bindAddress(AbstractHttpServerTransport.java:218)
            at app//org.opensearch.http.AbstractHttpServerTransport.bindServer(AbstractHttpServerTransport.java:185)
            at app//org.opensearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:312)
            at app//org.opensearch.common.lifecycle.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:77)
            at app//org.opensearch.node.Node.start(Node.java:1508)
            at app//org.opensearch.security.test.helper.cluster.ClusterHelper$1.run(ClusterHelper.java:222)
            at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)

            Caused by:
            java.net.BindException: Address already in use
                at java.base/sun.nio.ch.Net.bind0(Native Method)
                at java.base/sun.nio.ch.Net.bind(Net.java:555)
                at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
                at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
                at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
                at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
                at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
                at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
                at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
                at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
                at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                ... 1 more

org.opensearch.security.InitializationIntegrationTests > testWhoAmI FAILED
    javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
    See https://opensearch.org/docs/latest/clients/java-rest-high-level/ for troubleshooting.
        at __randomizedtesting.SeedInfo.seed([7BF73791BE9626EB:AF3993A8F95A324A]:0)
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:1030)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:342)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:330)
        at org.opensearch.security.InitializationIntegrationTests.testWhoAmI(InitializationIntegrationTests.java:141)

        Caused by:
        javax.net.ssl.SSLHandshakeException: Cipher suite `TLS_DHE_RSA_WITH_AES_256_CBC_SHA256` does not provide adequate security for HTTP/2
            at org.apache.hc.client5.http.ssl.AbstractClientTlsStrategy.lambda$upgrade$1(AbstractClientTlsStrategy.java:153)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:425)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession.access$100(SSLIOSession.java:74)
            at org.apache.hc.core5.reactor.ssl.SSLIOSession$1.inputReady(SSLIOSession.java:201)
            at org.apache.hc.core5.reactor.InternalDataChannel.onIOEvent(InternalDataChannel.java:142)
            at org.apache.hc.core5.reactor.InternalChannel.handleIOEvent(InternalChannel.java:51)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.processEvents(SingleCoreIOReactor.java:178)
            at org.apache.hc.core5.reactor.SingleCoreIOReactor.doExecute(SingleCoreIOReactor.java:127)
            at org.apache.hc.core5.reactor.AbstractSingleCoreIOReactor.execute(AbstractSingleCoreIOReactor.java:86)
            at org.apache.hc.core5.reactor.IOReactorWorker.run(IOReactorWorker.java:44)
            at java.base/java.lang.Thread.run(Thread.java:840)
```

1 Install JDK 11/JDK 17
2 Install other dependencies
sudo yum install -y git gcc make java-17-openjdk-devel python39 python39-devel bzip2-devel zlib-devel openssl-devel
3 Clone the repository
4 cd security
5 ./gradlew build -x test -x integrationTest -x :spotbugsIntegrationTest
6 ./gradlew test

I would like to know if there is any other test setup required to run unit tests or I'm missing any configuration steps/dependencies.
Any suggestions and pointers regarding the same will be helpful.

**Comment by scrawfor99** [comment]
[Triage] Hi @pratiktonage, thank you for filing this issue. Looking at the logs you can see that it reads "java.net.BindException: Address already in use". Based on that and the above message about the port (8743) you will want to check that you have configured the ports you used properly or turned off anything else you are running on the same ports. 

I am going to close this issue but please open a new one if you find an outstanding bug etc. You can also checkout the public forum for more help with configuration: https://forum.opensearch.org/

**Comment by sumitd2** [comment]
Hi @scrawfor99, I ran the following script a few times in a fresh Ubuntu 22.04 container. The number of tests that fail are different each time, and the best I could get is 2 failing tests. The errors are mostly the same "Address already in use". Before every run I checked the open ports with the `netstat -p` command and the output was clear. I suspect the individual tests dont close the ports properly, but its a bit surprising that things are working fine in your CI. Please let me know if I am missing something:

```
set -ex
apt update -y
DEBIAN_FRONTEND=noninteractive apt install git libbz2-dev zlib1g-dev libssl-dev build-essential python3 openjdk-17-jdk -y
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
git clone https://github.com/opensearch-project/security
cd security
./gradlew clean assemble
./gradlew test
```

**Comment by sumitd2** [comment]
Hi @scrawfor99 can you please help?
