### ISSUE TITLE
[BUG] Defaut tests which extend OpenSearchTestCase don't work

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4077]
**What is the bug?**

If you tray to create any test which extends `OpenSearchTestCase` such test failes with such exception:
```java

java.lang.RuntimeException: unable to install test security manager
	at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:199)
	at org.opensearch.test.OpenSearchTestCase.<clinit>(OpenSearchTestCase.java:275)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Caused by: java.lang.IllegalStateException: codebase property already set: codebase.kafka-server-common -> file:/home/ples/.gradle/caches/modules-2/files-2.1/org.apache.kafka/kafka-server-common/3.6.1/4895f6df5be60ec4aba3a006c9e75f159ca3abe2/kafka-server-common-3.6.1.jar, cannot set to file:/home/ples/.gradle/caches/modules-2/files-2.1/org.apache.kafka/kafka-server-common/3.6.1/dfd281eed4ceeb9131fa0a9bb1ff315cc4b802f7/kafka-server-common-3.6.1-test.jar
	at org.opensearch.bootstrap.Security.readPolicy(Security.java:249)
	at org.opensearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:165)
	... 4 more

```

**How can one reproduce the bug?**
Create any test which extends `OpenSearchTestCase` 

**What is the expected behavior?**
Such tests can be created and executed.

**Comment by derek-ho** [comment]
[Triage] Thanks for filing this issue! It seems that this is related to jar hell and this is definitely something we want to support in the security plugin. It seems that it may be related to kafka and seeing where it is being imported may be the root cause

**Comment by willyborankin** [comment]
The problem is on OpenSearch side.

**Comment by peternied** [comment]
@willyborankin While we wait for the fix, lets disable the test case to get this change in.  I've just pushed a commit to do this.

**Comment by peternied** [comment]
- Resolving, this was fixed in https://github.com/opensearch-project/OpenSearch/pull/12586
