### ISSUE TITLE
validateSecurityRolesWithMutableRolesMappingConfig is flaky

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#4103]
### Description
While looking into test failures on another PR I noticed that the following test case seems to fail multiple times on every test run. [1]
  In this PR I added extra logging for the test to printout the error message which produces the following output, see [raw logs](https://github.com/opensearch-project/security/actions/runs/8209924713/job/22456426854?pr=4102).

```
org.opensearch.security.dlic.rest.api.InternalUsersApiActionValidationTest > validateSecurityRolesWithMutableRolesMappingConfig FAILED
    java.lang.AssertionError: Expected valid result, error message: {
      "status" : "FORBIDDEN",
      "message" : "Resource 'all_access' is static."
    }
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.security.dlic.rest.api.InternalUsersApiActionValidationTest.assertValidationResultIsValid(InternalUsersApiActionValidationTest.java:171)
        at org.opensearch.security.dlic.rest.api.InternalUsersApiActionValidationTest.validateSecurityRolesWithMutableRolesMappingConfig(InternalUsersApiActionValidationTest.java:161)
```

### Reproduction
 Run test in the CI and check the output logs `dlicRestApiTest`, it doesn't seem to fail enough to fail PRs from getting approved, but its listed in the test failures output seemingly at least once per run on github runners.  I was unable to reproduce locally by running `% ./gradlew test --tests org.opensearch.security.dlic.rest.api.InternalUsersApiActionValidationTest.validateSecurityRolesWithMutableRolesMappingConfig                                                                                        /local/home/petern/git/security`

### Expected Result
The test should not be reported as having any failures.

### Additional Context

- Impacted PR [1] https://github.com/opensearch-project/security/pull/4102

**Comment by peternied** [comment]
@willyborankin could you look into this issue?

**Comment by willyborankin** [comment]
Hmmm this is strange. I cant reproduce it :-(

**Comment by peternied** [comment]
I was also unable to reproduce this issue locally, I have only seen these failures on GitHub Action runners.  Look at the latest execution of #4002's `test (dlicRestApiTest, windows/ubuntu-latest, 11/15/21)` all six of them show failure that resolved on re-run, e.g: 

```
Tests with failures:
 - org.opensearch.security.dlic.rest.api.InternalUsersApiActionValidationTest.validateSecurityRolesWithMutableRolesMappingConfig
 - org.opensearch.security.dlic.rest.api.SecurityConfigApiActionTest.testSecurityConfigApiReadForSuperAdmin
 ```

**Comment by willyborankin** [comment]
I will add logging to #4002 lets see

**Comment by scrawfor99** [comment]
[Triage] Hi @peternied thanks for filing this flaky test. Looks like investigation is in progress but we can close this when it is fixed or if it turns out to be a non-issue.
