### ISSUE TITLE
[BUG] Quiet offten our integration tests fail with `Address already in use` message

### ISSUE THREAD

**Issue by willyborankin** [opensearch-project/security#4185]
**What is the bug?**
Our integration tests quite often fil with such message:
```java
org.opensearch.security.PrivilegesEvaluationTest > resolveTestHidden FAILED
    java.lang.RuntimeException: Could not start all nodes BindHttpException[Failed to bind to [::1]:9017]; nested: BindException[Address already in use];
        at __randomizedtesting.SeedInfo.seed([2A8A334058CF3506:372891963547AE92]:0)
        at org.opensearch.security.test.helper.cluster.ClusterHelper.startCluster(ClusterHelper.java:273)
        at org.opensearch.security.test.helper.cluster.ClusterHelper.startCluster(ClusterHelper.java:124)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:107)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:83)
        at org.opensearch.security.test.SingleClusterTest.setup(SingleClusterTest.java:69)
        at org.opensearch.security.PrivilegesEvaluationTest.resolveTestHidden(PrivilegesEvaluationTest.java:30)
``` 
which is a bug.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by scrawfor99** [comment]
[Triage] Hi @willyborankin, thanks for filing this issue. Looks like some of the tests are not cleaning up properly. Someone will need to take a look to help stop this from becoming a frequent issue.

**Comment by willyborankin** [comment]
I investigated some failures. So far it looks like that old framework has such problems.
