### ISSUE TITLE
Test failure: InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest > canNotCreateUsersWithPassword

### ISSUE THREAD

**Issue by nibix** [opensearch-project/security#4547]
In the CI runs, I frequently get this test failure:

```
2024-07-10T14:35:11.7643547Z InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest > canNotCreateUsersWithPassword FAILED
2024-07-10T14:35:11.7644802Z     java.lang.AssertionError: {"status":"error","reason":"xxxxxxxx"}
2024-07-10T14:35:11.7645567Z     Expected: is "Weak password"
2024-07-10T14:35:11.7646078Z          but: was "xxxxxxxx"
2024-07-10T14:35:11.7646812Z         at __randomizedtesting.SeedInfo.seed([FFA6ACC85A323562:737CEB709138605]:0)
2024-07-10T14:35:11.7648078Z         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
2024-07-10T14:35:11.7649635Z         at org.opensearch.security.api.AbstractApiIntegrationTest.badRequestWithReason(AbstractApiIntegrationTest.java:290)
2024-07-10T14:35:11.7652119Z         at org.opensearch.security.api.InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest.lambda$canNotCreateUsersWithPassword$4(InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest.java:50)
2024-07-10T14:35:11.7654551Z         at org.opensearch.security.api.AbstractApiIntegrationTest.withUser(AbstractApiIntegrationTest.java:235)
2024-07-10T14:35:11.7656149Z         at org.opensearch.security.api.AbstractApiIntegrationTest.withUser(AbstractApiIntegrationTest.java:229)
2024-07-10T14:35:11.7658524Z         at org.opensearch.security.api.InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest.canNotCreateUsersWithPassword(InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest.java:49)
2024-07-10T14:35:11.8639050Z 
```

It is caused by another test, `InternalUsersRegExpPasswordRulesRestApiIntegrationTest`, modifying the static property `clusterSettings` of the shared super-class `AbstractApiIntegrationTest`.

Depending on which class is loaded first, `InternalUsersScoreBasedPasswordRulesRestApiIntegrationTest` is executed without the bad config modification and "wins", or it gets the config modification and fails with the above error.

I am not sure how this can be solved using the existing test infrastructure. Personally, however, I believe that using super-classes to provide shared functionality to unit-test classes is an anti-pattern, as it imposes many restrictions. One should follow the paradigm "composition over inheritance" for test classes.

**Comment by cwperks** [comment]
[Triage] Thank you for filing this issue!
