### ISSUE TITLE
[BUG] Continuous SSL exceptions post upgrade from 2.11 to 2.15

### ISSUE THREAD

**Issue by blueish-eyez** [opensearch-project/security#4718]
### Describe the bug

I had a working cluster free of errors, however post upgrade to 2.15 (also tested 2.16) I'm getting a ton of the following error on worker nodes:

```
[2024-08-12T16:48:40,662][ERROR][o.o.h.n.s.SecureNetty4HttpServerTransport] [opensearch-0] Exception during establishing a SSL connection: java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[?:?]
	at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:156) ~[transport-netty4-client-2.16.0.jar:2.16.0]
	at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:141) ~[transport-netty4-client-2.16.0.jar:2.16.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.111.Final.jar:4.1.111.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

This message is always identical and I cannot pinpoint it to a specific action performed by OpenSearch. The only thing that's also repeatedly logged is:

```
[INFO ][o.o.j.s.JobSweeper       ] [opensearch-0] Running full sweep
```

But I feel it's a long shot.

I did not see this problem on 2.11 and this only started appearing after upgrading. Has anyone else experienced this? Is there any direction you could recommend me to go other than verifying certificates (already done, none expired, CAs are there, as well as the keys etc). Is there perhaps a way to connect the SSL exception with a specific task that caused it? Was it communication from a specific node? From master node maybe? Was it in regards to snapshots or whatever?

Any help is highly appreciated! 

### Related component

Other

### To Reproduce

1. Setup a working cluster on 2.11 with Security plugin
2. Upgrade the cluster to 2.15
3. Check worker node logs for SSL exceptions

### Expected behavior

No SSL exceptions post upgrade

### Additional Details

**Plugins**
Security plugin

**Screenshots**

**Host/Environment (please complete the following information):**
 - Docker image based OpenSearch 2.15

**Additional context**

**Comment by reta** [comment]
@blueish-eyez the problem with `sslExceptionHandler` shoudl be fixed in 2.18.0 but it may not get rid of the this exceptions in the logs, fe I could reproduce (by simulation) those on 2.11.0:

```
[2024-09-10T19:45:25,650][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [21140679ffc1] Exception during establishing a SSL connection: java.net.SocketException: Connection reset                                                                                                                                                           
java.net.SocketException: Connection reset                                                                                                                                                                                                                                                                                                            
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]                                                                                                                                                                                                                                                       
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]                                                                                                                                                                                                                                                                       
        at org.opensearch.transport.CopyBytesSocketChannel.readFromSocketChannel(CopyBytesSocketChannel.java:156) ~[transport-netty4-client-2.11.0.jar:2.11.0]
        at org.opensearch.transport.CopyBytesSocketChannel.doReadBytes(CopyBytesSocketChannel.java:141) ~[transport-netty4-client-2.11.0.jar:2.11.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

By any chance, did you (re)configure logging on your clusters? One notable difference between 2.11.x and 2.15.x is that transports are now in different package.

**Comment by blueish-eyez** [comment]
@reta thanks for the update. Logging is configured at info level and I believe this was the baseline. No specific packages have elevated / suppressed messaging (except for testing that suggested @zane-neo in the first response, that however did not show any relevant messages around SSL exceptions). For the time being I can set `org.opensearch.http.netty4.ssl` to `FATAL` until I can get the 2.18 image to test with

**Comment by rlueckl** [comment]
FYI: we see the same exceptions (currently running 2.17, didn't check _when_ the exceptions were introduced in the logs).

A very simple way to reproduce - and how we noticed the exceptions in the first place: try the Nagios `check_http` plugin.
```
# /usr/lib/nagios/plugins/check_http -H opensearch-host01.int.lan --port=9200 --ssl --certificate=15
OK - Certificate 'opensearch-host01.int.lan' will expire on Sun 17 Nov 2024 06:05:05 AM GMT +0000.
```

Running the check will immediately trigger an exception. We didn't change anything in our monitoring and the `check_http` script wasn't updated for a long time either.

**Comment by reta** [comment]
@rlueckl thanks, could you reproduce it with docker setup? I cannot, the log is clean:

```
$ docker run -it -p 9200:9200 -p 9600:9600 -e OPENSEARCH_INITIAL_ADMIN_PASSWORD=_ad0m#Ns_ -e "discovery.type=single-node"  opensearchproject/opensearch:2.17.1
```

```
$ /usr/local/nagios/libexec/check_http  -H localhost --port=9200 --ssl --certificate=15
SSL OK - Certificate 'node-0.example.com' will expire in 3410 days on 2034-02-17 12:03 -0500/EST.

```

**Comment by rlueckl** [comment]
Hi @reta,
which version of `check_http` are you using? I've tested the docker image on my workstation but could not reproduce the issue, but my Linux Mint has a slightly older version of check_http than the servers.

check_http 2.3.1 (workstation) -> docker 2.17.0 (workstation) -> no exception
check_http 2.3.1 (workstation) -> docker 2.17.1 (workstation) -> no exception
check_http 2.3.1 (workstation) -> deb install 2.17.0 (server) -> no exception
check_http 2.3.3 (server) -> deb install 2.17.0 (server) -> _connection reset_ exception
check_http 2.3.3 (server) -> docker 2.17.x (workstation) -> can't test, firewall between the server and my workstation.

The last test would be interesting if you could test with check_http 2.3.3 and the docker image to see if there's an exception. Unfortunately I'm somewhat limited because of our company firewalls and can't test this case.

**Comment by reta** [comment]
> Hi @reta,
> which version of `check_http` are you using?

Thanks @rlueckl 

```
$ /usr/local/nagios/libexec/check_http  --version
check_http v2.4.11 (nagios-plugins 2.4.11)
```

I will try this configuration now, will update you shortly:
  - check_http 2.3.3 (server) -> deb install 2.17.0 (server) -> connection reset exception

**Comment by rlueckl** [comment]
Interesting. I can't reproduce the exception with 2.3.3 from my workstation, but running the check locally on the server I get the exception.

check_http 2.3.3 (server) -> deb install 2.17.0 (server) -> connection reset exception
check_http 2.3.3 (workstation) -> deb install 2.17.0 (server) -> no exception

**Comment by kkoki-ctrl** [comment]
I encountered the same error, and after checking, I found the following:

- The error occurs sporadically 0 to 3 times per hour, but only on the master node.
- The error happens regardless of the version (OpenSearch 2.13.0, 2.14.0, 2.16.0).
- The error does not occur when the elasticsearch-exporter:v1.8.0 is stopped.

https://forum.opensearch.org/t/ssl-exception-connection-reset-error-on-master-nodes/22281/5

**Comment by DarshitChanpura** [comment]
@reta I see that you are assigned to this issue and relevant PR: #4725 has been merged. Can we close this issue?

**Comment by reta** [comment]
> [@reta](https://github.com/reta) I see that you are assigned to this issue and relevant PR: [#4725](https://github.com/opensearch-project/security/pull/4725) has been merged. Can we close this issue?

Yeah, I think we could close this issue for now (no more reports), thank you @DarshitChanpura

**Comment by LHozzan** [comment]
Hi there.
Unfortunately, same problem here :(.
- I can observing it on our old previous setup with version `2.15.0` and on the new version `2.19.1`
- occurring randomly, most of the cases are on `coordinator` node type
- occurring on the single multi-role node as well
- OpenSearch instances are in Kubernetes clusters (I not tested the version in pure Docker on localhost)

I afraid, that all interesting information was provided from previous comments, but if you need something specify, please, let me know.
